### ISSUE TITLE
API Blueprint : Error parsing input: You can not register a basic element

### ISSUE THREAD

**Issue by WillSkates** [apiaryio/protagonist#166]
I'm having a weird situation where I cant use 'member' to label an object structure. Is 'member' a reserved word?

This will throw the error in the title:

```apib
## `member` (object)
```

This will parse without issue:

```apib
## `member-basic` (object)
```

**Comment by kylef** [comment]
Hi @WillSkates,

I do believe it is a reserved keyword. You can see it listed as such in the MSON specification (https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md#6-reserved-characters--keywords).

> ## 6 Reserved Characters & Keywords
> When using following characters or keywords in a _[Property Name][]_, _[Literal Value][]_ or _[Type Name][]_ the name or literal MUST be escaped in backticks `` ` ``. Otherwise, a `code span` MAY be used for any arbitrary formatting and has no specific meaning in an MSON document.
> 
> ### 6.1 Characters
> 
> `:`, `(`,`)`, `<`, `>`, `{`, `}`, `[`, `]`, `_`, `*`, `-`, `+`, `` ` ``
> 
> ### 6.2 Keywords
> 
> `Property`, `Properties`, `Item`, `Items`, `Member`, `Members`, `Include`, `One of`, `Sample`
> 
> Note keywords are case-insensitive.
> 
> ### 6.3 Additional Keywords
> Following keywords are reserved for future use:
> 
> `Trait`, `Traits`, `Parameter`, `Parameters`, `Attribute`, `Attributes`, `Filter`, `Validation`, `Choice`, `Choices`, `Enumeration`, `Enum`, `Object`, `Array`, `Element`, `Elements`, `Description`

**Comment by kylef** [comment]
The reason some of these keywords are reserved, is because it could be difficult for the MSON parser to know the difference. For example in the following case:

```apib
## Data Structures
### Foo (enum)
### Members

+ a
+ b
```

Members here is actually parsed as the members inside my enum `Foo`. However, in the following case:

```apib
## Data Structures
### Foo (enum)
### MyObj

+ a
+ b
```

`MyObj` is actually a separate object and `Foo` is an enum with no members.

---

That said, the following API Blueprint will raise an unintuitive error message, I would treat this as a bug in [Drafter](https://github.com/apiaryio/drafter) the underlying API Blueprint parser. We should improve the error message to make it clear to users that they are using reserved keywords incorrectly in cases we can detect.

```apib
## Data Structures
### member (object)
```

```
error: (4)  You can not register a basic element
```

However, if I use `member` as titlecase I don't get an error at all:

```apib
## Data Structures
### Member (object)
```

**Comment by pksunkara** [comment]
Tracking it in https://github.com/apiaryio/drafter/issues/401
