### ISSUE TITLE
Returning  null 

### ISSUE THREAD

**Issue by im-sunil** [apiaryio/protagonist#258]
```js 
const protagonist = require('protagonist');

protagonist.validate('# My API')
  .then((parseResult) => {
    console.log(JSON.stringify(parseResult, null, 2));
  })
  .catch((error) => {
    console.error(error);
  });
```

Example in Readme section return  null 

"protagonist": "^2.2.1"

**Comment by kylef** [comment]
`# My API` has no warnings or errors, thus for validation operation it is success and there isn’t a parse result (since there would be no warnings or errors). If you change the source API Blueprint to contain a validation warning or error then you should see a parseResult with the annotations.

For example:

```js

const protagonist = require('protagonist');

protagonist.validate('\ttabs are not allowed')
  .then((parseResult) => {
    console.log(JSON.stringify(parseResult, null, 2));
  })
  .catch((error) => {
    console.error(error);
  });
```
