### ISSUE TITLE
Parsing issue with array of custom types

### ISSUE THREAD

**Issue by tavisca-ashedge** [apiaryio/protagonist#261]
I have below content in apib file. Issue is after parsing 'persons ' is showing type as array only (not array of personsInfo)
because of this personsInfo types are not resolved

`
## persons (object)
+ persons (array [personsInfo], required) - Contains the list of information.

## personsInfo (object)
+ type (enum, required) - Type of guest
  + Adult
  + Child
+ age: 25 (number)

`
I'm using protagonist 1.6.8

current output:   type: array
expected output: type:array(personsInfo)

Please help

**Comment by kylef** [comment]
Protagonist 1.x is unsupported. Please upgrade to Protagonist is 2.2.1. The last Protagonist 1.x release was in 2017 (3 years ago).

If you want to define an array which may only contain a specific type, then you may want to use the [`fixed-type` keyword](https://apiblueprint.org/documentation/mson/cheatsheet.html#arrays). For example to describe an array which may only contain an object which must have a name property, the following MSON can be used:

```apib
+ Attributes (array, fixed-type)
    + (object)
        + name (required)
```

Without `fixed-type`, an array may contain any type. Any specific types are example values instead of typing.

**Comment by tavisca-ashedge** [comment]
This works
