### ISSUE TITLE
Navigating to an index reported by warnings

### ISSUE THREAD

**Issue by seglo** [apiaryio/protagonist#82]
Hey,

I have a large API document that I'm using `hercule` to transclude together.  I'm using `aglio` to generate documentation and it's working, but I get warnings that are from `protagonist`.  I would like to troubleshoot the warnings it's describing, but I don't know how to make use of the information it gives me.

In the `protagonist` readme it says a warning index represents:

> Zero-based index of the character where the warning occurs

But for a warning like this:

```javascript
{
    "code": 5,
    "message": "ignoring additional request header(s), specify this header(s) in the referenced model definition instead",
    "location": [
      {
        "index": 21262,
        "length": 17
      }
    ]
  }
```

How am I supposed to find index 21262?  My transcluded document has line breaks.  I'm using sublime to navigate it, but I can only navigate by col:row syntax - not an offset from the beginning of the file.  

Please advise how I can better make use of this warning info?

**Comment by seglo** [comment]
This appears to be a duplicate of https://github.com/apiaryio/protagonist/issues/68

**Comment by zdne** [comment]
Hey @seglo you can get to the the col:row syntax by either counting it manually or using the [Drafter CLI tool](https://github.com/apiaryio/drafter#command-line-tool). 

However with the file being concatenated by Hercule into one big blob the information won't be really helpful. Basically what is needed there is another source map, mapping positions from the concatenated blob to original files. 

Hercule can help here by providing the map but since Protagonist won't know how to work with it you will have to do the math by hand again :(

Something to be solved with https://github.com/apiaryio/api-blueprint/issues/8

**Comment by seglo** [comment]
The problem isn't so much the transclusion, although I agree that's something else that should be addressed upstream.  I can export my transcluded document and lookup offsets, it's just an inconvenience because I'm not using `drafter`, I'm using `aglio` with makes use of `protagonist` directly.  My workaround is to use vim to look at the transcluded document and then `goto: [offset]`.

**Comment by zdne** [comment]
@seglo I see. Generally I would suggest it is up to the tool using blueprint parser (drafter or protagonist) to utilize the source maps in a certain way. Following this principle I'd ask for this feature in Aglio..
